<?xml version="1.0" encoding="utf-8"?><Database Name="MVVMLoginDb" Class="POSDbDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\MSSQLSERVER01;Initial Catalog=MVVMLoginDb;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="LoginForm.Properties.Settings" SettingsPropertyName="MVVMLoginDbConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Brands" Member="Brands">
    <Type Name="Brand">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(191)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(191)" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Category_Category" Member="Categories" ThisKey="Id" OtherKey="ParentId" Type="Category" />
      <Association Name="Category_Category" Member="Category1" ThisKey="ParentId" OtherKey="Id" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Units" Member="Units">
    <Type Name="Unit">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UnitCode" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="UnitName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="BaseUnit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Operator" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>